version: "3.5"
services:
  app:
      container_name: laravel-cashier-app
      image: laravel-cashier:1.0
      restart: always
      tty: true
      ports:
        - "9000:9000"
      volumes:
        - 'laravel-cashier:/var/www/laravel-cashier/'
  web-server:
      container_name: nginx-cashier
      image: nginx:latest
      # restart: always
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
      volumes:
        - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        - 'laravel-cashier:/var/www/laravel-cashier/'
    


volumes:
  laravel-cashier:
    driver: local